<!DOCTYPE html>
<html lang="en">
<title>Sharon's Authentic Research</title> 
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<link rel="stylesheet" type="text/css" href="/styles/radfs_sar.css">


<style>
<!-- html,body,h1,h2,h3,h4,h5,h6 {font-family: "Roboto", sans-serif;}
.w3-sidebar {
  z-index: 3;
  width: 250px;
  top: 43px;
  bottom: 0;
  height: inherit;
} -->

img {
	
	
	float:left ;
}

a{
	
	padding:5px ;
}


</style>
<body>

<!-- Navbar -->
<div class="w3-top">
  <div class="w3-bar w3-theme w3-top w3-left-align w3-large">
    <a class="w3-bar-item w3-button w3-right w3-hide-large w3-hover-white w3-large w3-theme-l1" href="javascript:void(0)" onclick="w3_open()"><i class="fa fa-bars"></i></a>
    
	<img src="ASR_logo.jpg" width="100" height="43">
	<!-- a href="#" class="w3-bar-item w3-button w3-theme-l1">Logo</a> -->
    <a href="POC_SAR_about.PHP" class="w3-bar-item w3-button w3-hide-small w3-hover-white">About</a>
    <a href="POC_SAR_Writings.PHP" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Download/Upload Articles</a>
	<a href="POC_SAR_Partners.PHP" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Partners</a>
	
	<a href="POC_SAR_Reviews.PHP" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Stakeholder Feedback</a>
    <a href="POC_SAR_Payment gateway.PHP" class="w3-bar-item w3-button w3-hide-small w3-hover-white" style="float:right; color:red;">Payment Options</a>
   <!-- <a href="#" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Contact</a>
    <a href="#" class="w3-bar-item w3-button w3-hide-small w3-hide-medium w3-hover-white">Clients</a>
    <a href="#" class="w3-bar-item w3-button w3-hide-small w3-hide-medium w3-hover-white">Partners</a>  -->
  </div>
</div>

<!-- Sidebar -->
<nav class="w3-sidebar w3-bar-block w3-collapse w3-large w3-theme-l5 w3-animate-left" id="mySidebar">
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-right w3-xlarge w3-padding-large w3-hover-black w3-hide-large" title="Close Menu">
    <i class="fa fa-remove"></i>
  </a>
  <h4 class="w3-bar-item"><b>Menu</b></h4>
  <a class="w3-bar-item w3-button w3-hover-black" href="#">Executive Summary</a>
  <a class="w3-bar-item w3-button w3-hover-black" href="#radfs0001"">Sample of Writings</a>
  <!-- <a class="w3-bar-item w3-button w3-hover-black" href="#">Link</a>
  <a class="w3-bar-item w3-button w3-hover-black" href="#">Link</a> -->
</nav>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- Main content: shift it to the right by 250 pixels when the sidebar is visible -->
<div class="w3-main" style="margin-left:250px">

  <div class="w3-row w3-padding-64">
    <div class="w3-twothird w3-container">
      <h1 class="w3-text-teal">Executive Summary</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum
        dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    
	<p>Vestibulum a rutrum erat. Nullam et urna nec augue lobortis hendrerit. Donec a consectetur mauris. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer scelerisque iaculis purus, eget tempus nibh sodales nec. Mauris ornare nisl a sapien sodales laoreet. Aliquam lacus nisi, malesuada non diam nec, sodales viverra libero. Proin justo erat, malesuada vel tellus a, varius facilisis dui. Pellentesque  habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque dapibus sed diam id finibus. Fusce tortor ante, commodo viverra urna in, euismod congue urna. Quisque pellentesque nisl nunc, vehicula finibus erat egestas et. Nullam volutpat justo ut ante fermentum semper. Mauris mollis rhoncus erat dictum dictum.</p>

<p>Vestibulum commodo at ipsum sed ornare. Sed eleifend neque eget euismod mattis. Integer ligula turpis, lacinia aliquam augue eu, faucibus tincidunt neque. Pellentesque varius risus vel gravida rhoncus. Praesent fermentum mi id eleifend sollicitudin. Etiam id hendrerit leo, id dapibus dolor. Phasellus vestibulum nisl ac lectus vulputate rutrum. Nunc ut libero et arcu scelerisque porta. Fusce porttitor est ut malesuada rhoncus. Vestibulum a est non sapien rutrum mollis commodo eu orci. Mauris fringilla scelerisque tellus et pretium. Maecenas orci libero, imperdiet non vestibulum et, pulvinar a augue.</p>

<p>Nullam fermentum est non elit finibus interdum. Sed auctor, neque nec viverra feugiat, risus sapien laoreet risus, nec mattis dui est nec nisl. Aenean ornare lorem in mauris dictum lobortis. Ut id tincidunt est, mollis blandit nisl. In risus risus, consequat at leo a, euismod mattis leo. Fusce non quam vehicula, maximus nulla ut, congue nunc. Aliquam eget tortor ut ipsum suscipit dictum. Sed pulvinar placerat mi, nec imperdiet arcu pellentesque quis.</p>
	
	
	
	
	</div>
    <div style="text-align:left;">
      <!-- <p class="w3-border w3-padding-large w3-padding-32 w3-center"> -->
	  
	 <h6 id="quot"><u>Quotes (Sharon Campbell-Phillips) </u></h6>
	  <pre style="color:#9C0B0E;">
A person without knowledge is merely
existing,a life that flourishes, 
is one with wisdom.

Wisdom creates all things; knowledge allows
you to excel

Great is he who seeketh knowledge, wise 
is he who use it creatively
		
	
	  
	  </pre>
	
	
	
      <!-- <p class="w3-border w3-padding-large w3-padding-64 w3-center">AD</p> -->
    </div>
  </div>

  <!-- <div class="w3-row"> -->
  <div>
    <div class="w3-twothird w3-container">
      <h1 id="radfs0001" class="w3-text-teal">Sample of Writings</h1>
      <p ><b><u>Published Writings</u></b></p>

		<iframe src="https://publons.com/researcher/3328531/sharon-campbell-phillips/" width="700" ,height="400"></iframe>
		
		
	</div>
    <div class="w3-third w3-container">
		<!-- <p class="w3-border w3-padding-large w3-padding-32 w3-center">AD</p>
      <p class="w3-border w3-padding-large w3-padding-64 w3-center">AD</p> -->
    </div>
  </div>

  <div class="w3-row w3-padding-64">
    <div class="w3-twothird w3-container">
      <h6 class="w3-text-teal">Synopsis of writings</h6>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum
        dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    </div>
    <div class="w3-third w3-container">
      <!-- <p class="w3-border w3-padding-large w3-padding-32 w3-center">AD</p>
      <p class="w3-border w3-padding-large w3-padding-64 w3-center">AD</p>  -->
    </div>
  </div>

  <!-- Pagination -->
  <div class="w3-center w3-padding-32">
    <div class="w3-bar">
      <a class="w3-button w3-green" href="#">1</a>
      <a class="w3-button  w3-hover-black" href="POC_SAR_about.PHP">2</a>
      <a class="w3-button w3-hover-black" href="POC_SAR_Writings.PHP">3</a>
      <a class="w3-button w3-hover-black" href="POC_SAR_Partners.PHP">4</a>
	    <a class="w3-button w3-hover-black" href="POC_SAR_Reviews.PHP">5</a>
      <a class="w3-button w3-hover-black" href="POC_SAR_Payment gateway.PHP">6</a>
      <a class="w3-button w3-hover-black" href="POC_SAR_about.PHP">»</a>
    </div>
  </div>
<button  class="w3-button w3-purple w3-round" onclick="topFunction()" id="myBtn" title="Go to top">Top</button>
  <footer id="myFooter">
   <!-- <div class="w3-container w3-theme-l2 w3-padding-32">
      <h4>Footer</h4>
    </div> -->

    <div class="w3-container w3-theme-l1">
      <p>Powered by &copy RAD Financial Systems</p>
    </div>
  </footer>

<!-- END MAIN -->



</div>

<script>
// Get the Sidebar
var mySidebar = document.getElementById("mySidebar");

// Get the DIV with overlay effect
var overlayBg = document.getElementById("myOverlay");

// Toggle between showing and hiding the sidebar, and add overlay effect
function w3_open() {
  if (mySidebar.style.display === 'block') {
    mySidebar.style.display = 'none';
    overlayBg.style.display = "none";
  } else {
    mySidebar.style.display = 'block';
    overlayBg.style.display = "block";
  }
}

// Close the sidebar with the close button
function w3_close() {
  mySidebar.style.display = "none";
  overlayBg.style.display = "none";
}




//Get the button
var mybutton = document.getElementById("myBtn");

// When the user scrolls down 20px from the top of the document, show the button
window.onscroll = function() {scrollFunction()};

function scrollFunction() {
  if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
    mybutton.style.display = "block";
  } else {
    mybutton.style.display = "none";
  }
}

// When the user clicks on the button, scroll to the top of the document
function topFunction() {
  document.body.scrollTop = 0;
  document.documentElement.scrollTop = 0;
}
</script>


</body>
</html>
 