<!doctype html lang="en-TT">

<html>

<head>
		<title>Sharon's Authentic Research - Download</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="device=device-width , initial-scale=1">
		
		<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
		<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
		
		
		
		<style>
				html,body,h1,h2,h3,h4,h5,h6 {font-family: "Roboto", sans-serif;}
				.w3-sidebar {
				  z-index: 3;
				  width: 250px;
				  top: 43px;
				  bottom: 0;
				 <!--  height: inherit; -->

				button {
					 
					 
					  width: 200px ; 
				 }
				  
			}
		</style>


		<script type="text/javascript" src="js/lib_gen_code.js"></script>

	</head>


<body>

	
<!-- Navbar -->
<div class="w3-top">
  <div class="w3-bar w3-theme w3-top w3-left-align w3-large">
    <a class="w3-bar-item w3-button w3-right w3-hide-large w3-hover-white w3-large w3-theme-l1" href="javascript:void(0)" onclick="w3_open()"><i class="fa fa-bars"></i></a>
    
	
	<!-- a href="#" class="w3-bar-item w3-button w3-theme-l1">Logo</a> -->
    <h6 style="text-align:center; color:yellow;">S.A.R Files for Downloading</h6>
    <!-- <a href="#" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Values</a>
    <a href="#" class="w3-bar-item w3-button w3-hide-small w3-hover-white">News</a>
    <a href="#" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Contact</a>
    <a href="#" class="w3-bar-item w3-button w3-hide-small w3-hide-medium w3-hover-white">Clients</a>
    <a href="#" class="w3-bar-item w3-button w3-hide-small w3-hide-medium w3-hover-white">Partners</a> -->
  </div>
</div>

<!-- Sidebar -->
<nav class="w3-sidebar w3-bar-block w3-collapse w3-large w3-theme-l5 w3-animate-left" id="mySidebar">
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-right w3-xlarge w3-padding-large w3-hover-black w3-hide-large" title="Close Menu">
    <i class="fa fa-remove"></i>
  </a>
  <h4 class="w3-bar-item"><b>Menu</b></h4>
  <!--
<a class="w3-bar-item w3-button w3-hover-black" href="#radfs0003">Credit/Debit Card Payment(s)</a>
<a class="w3-bar-item w3-button w3-hover-black" href="#radfs0002">Cash Payment Vouchers</a>
<a class="w3-bar-item w3-button w3-hover-black" href="#radfs0004">Point of Sale</a> 
<a class="w3-bar-item w3-button w3-hover-black" href="#radfs0005">Money Transfer</a> -->
  <hr/>
  
   <a class="w3-bar-item w3-button w3-hover-black" style="color: red;" href="POC_SAR_Writings.PHP">Back</a>
</nav>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- Main content: shift it to the right by 250 pixels when the sidebar is visible -->
<div class="w3-main" style="margin-left:250px">


<p id="radfs0003"></p>
  <div class="w3-row w3-padding-64">
  
  <h1 style="font-size:180% ;">Files For Download (Demo)</h1>
    <div class="w3-twothird w3-container">
	
	
	
	
      <!-- <h4  class="w3-text-teal">Demo 1</h4> -->
    
		<p  id="radfs0002" ></p>
    <div class="w3-third w3-container">
     	  
		<a href="file_download_manager_20200529_1447.php"><button class="w3-button w3-khaki" style="width:200px; height:100px;">Snapshots of website</button></a>
	  
    </div>
  </div>


 <div class="w3-twothird w3-container">
	
	
	
	
   <!--    <h4  class="w3-text-teal">Demo 1</h4>  -->
    
		<p  id="radfs0002" ></p>
    <div class="w3-third w3-container">
     	  
		<a href="file_download_manager_num2.php"><button class="w3-button w3-khaki" style="width:200px; height:100px;">R.A.D Fin. Sys logo</button></a>
	  
    </div>
  </div>

	 <div class="w3-twothird w3-container">
	
	
	
	
      <!--<h4  class="w3-text-teal">Demo 1</h4>-->
    
		<p  id="radfs0002" ></p>
    <div class="w3-third w3-container">
     	  
		 <a href="file_download_manager_num3.php"><button class="w3-button w3-khaki" style="width:200px; height:100px;">S.A.R logo</button></a>
	  
    </div>
  </div>
	
	
	
  <div class="w3-row">
    <div  class="w3-twothird w3-container">
      
    </div>
    <div class="w3-third w3-container">
     <!--  <p class="w3-border w3-padding-large w3-padding-32 w3-center">AD</p>
      <p class="w3-border w3-padding-large w3-padding-64 w3-center">AD</p> -->
    </div>
  </div>

	<p id="radfs0004" ></p>
  <div class="w3-row w3-padding-64">
    <div  class="w3-twothird w3-container">
     
    </div>
    <div class="w3-third w3-container">
     <!--  <p class="w3-border w3-padding-large w3-padding-32 w3-center">AD</p>
      <p class="w3-border w3-padding-large w3-padding-64 w3-center">AD</p> -->
    </div>
  </div>
  
  <p id="radfs0005"></p>
  <div class="w3-row w3-padding-64">
     
	  
    </div>
  </div>


  <!-- Pagination -->
  <div class="w3-center w3-padding-32">
    <div class="w3-bar">
      <a class="w3-button" href="POC_SAR.PHP">1</a>
      <a class="w3-button w3-hover-black" href="POC_SAR_about.PHP">2</a>
      <a class="w3-button w3-red w3-hover-black" href="#">3</a>
      <a class="w3-button w3-hover-black" href="POC_SAR_Partners.PHP">4</a>
      <a class="w3-button w3-hover-black" href="POC_SAR_Reviews.PHP">5</a>
	  <a class="w3-button   w3-hover-black" href="POC_SAR_Payment gateway.PHP">6</a>
      <a class="w3-button w3-hover-black" href="POC_SAR.PHP">»</a>
    </div>
  </div>
<button  class="w3-button w3-purple w3-round" onclick="topFunction()" id="myBtn" title="Go to top">Top</button>
  <footer id="myFooter">
    <div class="w3-container w3-theme-l2 w3-padding-8">
     <!--  <h4>Footer</h4> -->
    </div>

    <div class="w3-container w3-theme-l1">
      <p>Powered by &copy RAD Financial Systems</p>
    </div>
  </footer>
</div>
<!-- END MAIN -->
</div>

</DIV>

<script>
// Get the Sidebar
var mySidebar = document.getElementById("mySidebar");

// Get the DIV with overlay effect
var overlayBg = document.getElementById("myOverlay");

// Toggle between showing and hiding the sidebar, and add overlay effect
function w3_open() {
  if (mySidebar.style.display === 'block') {
    mySidebar.style.display = 'none';
    overlayBg.style.display = "none";
  } else {
    mySidebar.style.display = 'block';
    overlayBg.style.display = "block";
  }
}

// Close the sidebar with the close button
function w3_close() {
  mySidebar.style.display = "none";
  overlayBg.style.display = "none";
}




//Get the button
var mybutton = document.getElementById("myBtn");

// When the user scrolls down 20px from the top of the document, show the button
window.onscroll = function() {scrollFunction()};

function scrollFunction() {
  if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
    mybutton.style.display = "block";
  } else {
    mybutton.style.display = "none";
  }
}

// When the user clicks on the button, scroll to the top of the document
function topFunction() {
  document.body.scrollTop = 0;
  document.documentElement.scrollTop = 0;
}

</script>

	



</body>

</html>