<!DOCTYPE html lang="en-TT">


<html>

	<head>
		<title>Sharon's Authentic Research - About</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="device=device-width , initial-scale=1">
		
		<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
		<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
		
		<link rel="stylesheet" type="text/css" href="/styles/radfs_sar.css">
		
		<style>
<!--html,body,h1,h2,h3,h4,h5,h6 {font-family: "Roboto", sans-serif;}
				.w3-sidebar {
				  z-index: 3;
				  width: 250px;
				  top: 43px;
				  bottom: 0;
				 <!--  height: inherit; -->
				  
			}
		</style>


	</head>


<body>

	
<!-- Navbar -->
<div class="w3-top">
  <div class="w3-bar w3-theme w3-top w3-left-align w3-large">
    <a class="w3-bar-item w3-button w3-right w3-hide-large w3-hover-white w3-large w3-theme-l1" href="javascript:void(0)" onclick="w3_open()"><i class="fa fa-bars"></i></a>
    
	
	<!-- a href="#" class="w3-bar-item w3-button w3-theme-l1">Logo</a> -->
    <h6 style="text-align:center; color:yellow;">Sharon's Authenitic Research - Summary Overview</h6>
    <!-- <a href="#" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Values</a>
    <a href="#" class="w3-bar-item w3-button w3-hide-small w3-hover-white">News</a>
    <a href="#" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Contact</a>
    <a href="#" class="w3-bar-item w3-button w3-hide-small w3-hide-medium w3-hover-white">Clients</a>
    <a href="#" class="w3-bar-item w3-button w3-hide-small w3-hide-medium w3-hover-white">Partners</a> -->
  </div>
</div>

<!-- Sidebar -->
<nav class="w3-sidebar w3-bar-block w3-collapse w3-large w3-theme-l5 w3-animate-left" id="mySidebar">
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-right w3-xlarge w3-padding-large w3-hover-black w3-hide-large" title="Close Menu">
    <i class="fa fa-remove"></i>
  </a>
  <h4 class="w3-bar-item"><b>Menu</b></h4>
  <a class="w3-bar-item w3-button w3-hover-black" href="#radfs0003">Life Summary</a>
  <a class="w3-bar-item w3-button w3-hover-black" href="#radfs0002">Academic Life</a>
  <a class="w3-bar-item w3-button w3-hover-black" href="#radfs0004">Awards & Accoaldes</a>
  <a class="w3-bar-item w3-button w3-hover-black" href="#radfs0005">Future Projects</a>
  <hr/>
  
   <a class="w3-bar-item w3-button w3-hover-black" style="color: red;" href="POC_SAR.PHP">Landing Page</a>
</nav>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- Main content: shift it to the right by 250 pixels when the sidebar is visible -->
<div class="w3-main" style="margin-left:250px">


<p id="radfs0003"></p>
  <div class="w3-row w3-padding-64">
    <div class="w3-twothird w3-container">
	
	<iframe width="727" height="409" src="https://www.youtube.com/embed/TTF12ywSKWc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
	
	
      <h4  class="w3-text-teal">Life Summary</h4>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum
        dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
		
		
    <p>diAliquam lacinia vel ligula in auctor. Aliquam volutpat tincidunt leo, vitae scelerisque odio pulvinar mattis. Proin porttitor purus ut sapien porttitor ultrices. Curabitur ut ligula sodales, congue quam ut, aliquet ex. Sed tincidunt eu turpis at pulvinar. Proin ac ligula euismod eros dictum luctus. Suspendisse vitae hendrerit enim. Morbi erat ante, mollis et tristique eget, mattis non urna. Sed placerat arcu sed ultricies varius. Aenean iaculis malesuada purus, sit amet cursus augue tempor non. In hac habitasse platea dictumst. Vestibulum sit amet mattis odio, ut imperdiet arcu.</p>

<p>Proin euismod iaculis felis, ac mattis sem commodo ac. Pellentesque sagittis erat nibh, in viverra magna sodales nec. Vivamus posuere, eros quis tincidunt euismod, eros diam congue sapien, in maximus massa justo et augue. Mauris vel felis augue. Nulla hendrerit orci sit amet lorem sodales efficitur. Cras justo nibh, scelerisque ut libero eu, bibendum facilisis libero. Duis eget massa sed purus sagittis consequat sed quis velit. Aenean pretium purus ut ante imperdiet gravida. Donec eget urna mauris.</p>

<p>Maecenas blandit vel massa vitae vulputate. Nulla facilisis gravida lacus feugiat interdum. Morbi a porta magna. Fusce sagittis quis dolor in convallis. Mauris vel justo sit amet velit ultrices hendrerit. Mauris at sagittis enim, vitae finibus dolor. Nullam varius luctus enim, quis auctor arcu consectetur sed. Morbi consequat, libero sit amet gravida imperdiet, magna augue efficitur diam, eu varius felis tellus nec mi. Etiam augue eros, pellentesque a lectus mattis, commodo suscipit eros. Donec vehicula id sapien id venenatis. In placerat rutrum odio quis posuere. Integer dolor dui, aliquet nec viverra a, condimentum at lorem. Nullam eu tincidunt nibh. Nunc lobortis risus sed efficitur lacinia. Nulla facilisi.</p>

<p  id="radfs0002" >Fusce mauris turpis, rutrum eget accumsan non, varius lobortis dolor. Fusce libero est, ornare aliquam interdum sed, fermentum ornare dolor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer volutpat nisi ac ullamcorper suscipit. Aliquam id mi lectus. Proin laoreet ut mi eget tristique. Aenean mattis nunc a elit ornare, sit amet dictum libero dapibus. Donec gravida in sapien eget tempus. Donec ullamcorper turpis dignissim, porta massa non, pellentesque tortor. Proin bibendum varius nulla, quis tincidunt felis porttitor eu. Donec nec risus scelerisque, imperdiet sem sit amet, sollicitudin mauris. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed id est laoreet, volutpat felis ac, pharetra dui.</p>
    <div class="w3-third w3-container">
      <!-- <p class="w3-border w3-padding-large w3-padding-32 w3-center">AD</p>
      <p class="w3-border w3-padding-large w3-padding-64 w3-center">AD</p> -->
	  
    </div>
  </div>

	
  <div class="w3-row">
    <div  class="w3-twothird w3-container">
      <h4 class="w3-text-teal">Academic Life</h4>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum
        dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
		
		
		</p>
		
    </div>
    <div class="w3-third w3-container">
     <!--  <p class="w3-border w3-padding-large w3-padding-32 w3-center">AD</p>
      <p class="w3-border w3-padding-large w3-padding-64 w3-center">AD</p> -->
    </div>
  </div>

	<p id="radfs0004" ></p>
  <div class="w3-row w3-padding-64">
    <div  class="w3-twothird w3-container">
      <h4 class="w3-text-teal">Awards & Accolades</h4>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse venenatis luctus enim ut imperdiet. Aenean et lorem erat. Donec eu neque ut tellus placerat semper. Quisque dictum, neque vel facilisis blandit, elit nunc lacinia odio, at fringilla lorem dui non justo. Vestibulum tristique at risus et faucibus. Maecenas neque ipsum, interdum eget elementum eu, placerat a massa. Donec sed ultrices purus, nec dictum purus. Aenean malesuada, tellus sit amet tempus tincidunt, purus libero congue libero, vitae fermentum magna ante et diam. Nunc ac bibendum ipsum, quis fringilla neque. Ut luctus auctor mollis. Mauris tristique et nibh sed varius. Praesent interdum ante sed ultrices semper. Nulla vehicula semper tempor..</p>
    </div>
    <div class="w3-third w3-container">
     <!--  <p class="w3-border w3-padding-large w3-padding-32 w3-center">AD</p>
      <p class="w3-border w3-padding-large w3-padding-64 w3-center">AD</p> -->
    </div>
  </div>
  
  <p id="radfs0005"></p>
  <div class="w3-row w3-padding-64">
    <div    class="w3-twothird w3-container">
      <h4 class="w3-text-teal">Future Projects</h4>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse venenatis luctus enim ut imperdiet. Aenean et lorem erat. Donec eu neque ut tellus placerat semper. Quisque dictum, neque vel facilisis blandit, elit nunc lacinia odio, at fringilla lorem dui non justo. Vestibulum tristique at risus et faucibus. Maecenas neque ipsum, interdum eget elementum eu, placerat a massa. Donec sed ultrices purus, nec dictum purus. Aenean malesuada, tellus sit amet tempus tincidunt, purus libero congue libero, vitae fermentum magna ante et diam. Nunc ac bibendum ipsum, quis fringilla neque. Ut luctus auctor mollis. Mauris tristique et nibh sed varius. Praesent interdum ante sed ultrices semper. Nulla vehicula semper tempor..</p>
    </div>
    <div class="w3-third w3-container">
      <!-- <p class="w3-border w3-padding-large w3-padding-32 w3-center">AD</p>
      <p class="w3-border w3-padding-large w3-padding-64 w3-center">AD</p> -->
	  
	  
    </div>
  </div>


  <!-- Pagination -->
  <div class="w3-center w3-padding-32">
    <div class="w3-bar">
      <a class="w3-button" href="POC_SAR.PHP">1</a>
      <a class="w3-button w3-green w3-hover-black" href="#">2</a>
      <a class="w3-button w3-hover-black" href="POC_SAR_Writings.PHP">3</a>
      <a class="w3-button w3-hover-black" href="POC_SAR_Partners.PHP">4</a>
      <a class="w3-button w3-hover-black" href="POC_SAR_Reviews.PHP">5</a>
	  <a class="w3-button w3-hover-black" href="POC_SAR_Payment gateway.PHP">6</a>
      <a class="w3-button w3-hover-black" href="POC_SAR_Writings.PHP">»</a>
    </div>
  </div>

	<button class="w3-button w3-purple w3-round" onclick="topFunction()" id="myBtn" title="Go to top">Top</button>
  <footer id="myFooter">
    <div class="w3-container w3-theme-l2 w3-padding-8">
     <!--  <h4>Footer</h4> -->
    </div>

    <div class="w3-container w3-theme-l1">
      <p>Powered by &copy RAD Financial Systems</p>
    </div>
  </footer>
</div>
<!-- END MAIN -->
</div>

</DIV>

<script>
// Get the Sidebar
var mySidebar = document.getElementById("mySidebar");

// Get the DIV with overlay effect
var overlayBg = document.getElementById("myOverlay");

// Toggle between showing and hiding the sidebar, and add overlay effect
function w3_open() {
  if (mySidebar.style.display === 'block') {
    mySidebar.style.display = 'none';
    overlayBg.style.display = "none";
  } else {
    mySidebar.style.display = 'block';
    overlayBg.style.display = "block";
  }
}

// Close the sidebar with the close button
function w3_close() {
  mySidebar.style.display = "none";
  overlayBg.style.display = "none";
}



//Get the button
var mybutton = document.getElementById("myBtn");

// When the user scrolls down 20px from the top of the document, show the button
window.onscroll = function() {scrollFunction()};

function scrollFunction() {
  if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
    mybutton.style.display = "block";
  } else {
    mybutton.style.display = "none";
  }
}

// When the user clicks on the button, scroll to the top of the document
function topFunction() {
  document.body.scrollTop = 0;
  document.documentElement.scrollTop = 0;
}
</script>

	

</body>

</html>