<!doctype html lang="en-TT">

<html>

<head>
		<title>Sharon's Authentic Research - Partnerships</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="device=device-width , initial-scale=1">
		
		<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
		<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
		<link rel="stylesheet" type="text/css" href="/styles/radfs_sar.css">
		
	

	</head>


<body>

	
<!-- Navbar -->
<div class="w3-top">
  <div class="w3-bar w3-theme w3-top w3-left-align w3-large">
    <a class="w3-bar-item w3-button w3-right w3-hide-large w3-hover-white w3-large w3-theme-l1" href="javascript:void(0)" onclick="w3_open()"><i class="fa fa-bars"></i></a>
    
	
	<!-- a href="#" class="w3-bar-item w3-button w3-theme-l1">Logo</a> -->
    <h6 style="text-align:center; color:yellow;">S.A.R Partners</h6>
    <!-- <a href="#" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Values</a>
    <a href="#" class="w3-bar-item w3-button w3-hide-small w3-hover-white">News</a>
    <a href="#" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Contact</a>
    <a href="#" class="w3-bar-item w3-button w3-hide-small w3-hide-medium w3-hover-white">Clients</a>
    <a href="#" class="w3-bar-item w3-button w3-hide-small w3-hide-medium w3-hover-white">Partners</a> -->
  </div>
</div>

<!-- Sidebar -->
<nav class="w3-sidebar w3-bar-block w3-collapse w3-large w3-theme-l5 w3-animate-left" id="mySidebar">
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-right w3-xlarge w3-padding-large w3-hover-black w3-hide-large" title="Close Menu">
    <i class="fa fa-remove"></i>
  </a>
  <h4 class="w3-bar-item"><b>Menu</b></h4>
<a class="w3-bar-item w3-button w3-hover-black" href="#radfs0003">Publishers</a>
<a class="w3-bar-item w3-button w3-hover-black" href="#radfs0002">Academic Institutions</a>
<!-- <a class="w3-bar-item w3-button w3-hover-black" href="#radfs0004">Point of Sale</a> 
<a class="w3-bar-item w3-button w3-hover-black" href="#radfs0005">Money Transfer</a> -->
  <hr/>
  
   <a class="w3-bar-item w3-button w3-hover-black" style="color: red;" href="POC_SAR.PHP">Landing Page</a>
</nav>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- Main content: shift it to the right by 250 pixels when the sidebar is visible -->
<div class="w3-main" style="margin-left:250px">


<p id="radfs0003"></p>
  <div class="w3-row w3-padding-64">
    <div class="w3-twothird w3-container">
	
	
	
	
      <h4  class="w3-text-teal">Publishing Organisations</h4>
    
<p  id="radfs0002" >Works published via</p>
    <div class="w3-third w3-container">
      <!-- <p class="w3-border w3-padding-large w3-padding-32 w3-center">AD</p>
      <p class="w3-border w3-padding-large w3-padding-64 w3-center">AD</p> -->




		<a href="https://www.ingramspark.com/"> <img src="https://www.ingramspark.com/hubfs/IngramSpark_August_2016/Images/logo2x.png" width="300" height="100"/>
		</a>
	  
	  
	  
    </div>
  </div>

	
  <div class="w3-row">
    <div  class="w3-twothird w3-container">
      <h4 class="w3-text-teal">Academic Institutions</h4>
	  
      <p>Affiliated Universities </p>
	  <hr>
		

<a href="https://www.uopeople.edu/"> <img src="https://www.uopeople.edu/wp-content/themes/uopeople/assets/img/layout/logo_uopeople.png" width="300" height="100"/>
		</a>
		
		
		<a href="https://www.costaatt.edu.tt/"> <img src="https://www.costaatt.edu.tt/wp-content/uploads/2018/03/weblogo-300-01.jpg" width="300" height="100"/>
		</a>
	  		
    </div>
    <div class="w3-third w3-container">
     <!--  <p class="w3-border w3-padding-large w3-padding-32 w3-center">AD</p>
      <p class="w3-border w3-padding-large w3-padding-64 w3-center">AD</p> -->
    </div>
  </div>

	<p id="radfs0004" ></p>
  <div class="w3-row w3-padding-64">
    <!-- <div  class="w3-twothird w3-container">
      <h4 class="w3-text-teal">Point of Sale (POS)</h4>
      <p>Using WiPay POS technology</p>
	  <hr>
		<a href="https://wipaycaribbean.com/point-of-sale/" class="w3-bar-item w3-button w3-hide-small w3-hover-white" style="background-color:cyan;">WiPay POS</a>		
	 
    </div>
    <div class="w3-third w3-container">
     <!--  <p class="w3-border w3-padding-large w3-padding-32 w3-center">AD</p>
      <p class="w3-border w3-padding-large w3-padding-64 w3-center">AD</p> 
    </div> -->
  </div>
  
  <p id="radfs0005"></p>
  <div class="w3-row w3-padding-64">
   <!--  <div    class="w3-twothird w3-container">
      <h4 class="w3-text-teal">WiPay Money Transfer</h4>
      <p>For clients that want to use their own WiPay account to facilitate payment.</p>
	   <hr>
		<a href="https://wipaycaribbean.com/money-transfer/" class="w3-bar-item w3-button w3-hide-small w3-hover-white" style="background-color:cyan;">Money Transfer Accounts</a>		
	 
    </div>
    <div class="w3-third w3-container">
      <!-- <p class="w3-border w3-padding-large w3-padding-32 w3-center">AD</p>
      <p class="w3-border w3-padding-large w3-padding-64 w3-center">AD</p> 
	  
	  -->
	  
	  
    </div>
  </div>


  <!-- Pagination -->
  <div class="w3-center w3-padding-32">
    <div class="w3-bar">
      <a class="w3-button w3-hover-black" href="POC_SAR.PHP">1</a>
      <a class="w3-button w3-hover-black" href="POC_SAR_about.PHP">2</a>
      <a class="w3-button w3-hover-black" href="POC_SAR_Writings.PHP">3</a>
      <a class="w3-button w3-green w3-hover-black" href="#">4</a>
     <a class="w3-button w3-hover-black" href="POC_SAR_Reviews.PHP">5</a>
	  <a class="w3-button w3-hover-black" href="POC_SAR_Payment gateway.PHP">6</a>
	   <a class="w3-button w3-hover-black" href="POC_SAR_Reviews.PHP">»</a>
    </div>
  </div>



<button  class="w3-button w3-purple w3-round" onclick="topFunction()" id="myBtn" title="Go to top">Top</button>
  <footer id="myFooter">
    <div class="w3-container w3-theme-l2 w3-padding-8">
     <!--  <h4>Footer</h4> -->
    </div>

    <div class="w3-container w3-theme-l1">
      <p>Powered by &copy RAD Financial Systems</p>
    </div>
  </footer>
</div>
<!-- END MAIN -->
</div>

</DIV>

<script>
// Get the Sidebar
var mySidebar = document.getElementById("mySidebar");

// Get the DIV with overlay effect
var overlayBg = document.getElementById("myOverlay");

// Toggle between showing and hiding the sidebar, and add overlay effect
function w3_open() {
  if (mySidebar.style.display === 'block') {
    mySidebar.style.display = 'none';
    overlayBg.style.display = "none";
  } else {
    mySidebar.style.display = 'block';
    overlayBg.style.display = "block";
  }
}

// Close the sidebar with the close button
function w3_close() {
  mySidebar.style.display = "none";
  overlayBg.style.display = "none";
}



//Get the button
var mybutton = document.getElementById("myBtn");

// When the user scrolls down 20px from the top of the document, show the button
window.onscroll = function() {scrollFunction()};

function scrollFunction() {
  if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
    mybutton.style.display = "block";
  } else {
    mybutton.style.display = "none";
  }
}

// When the user clicks on the button, scroll to the top of the document
function topFunction() {
  document.body.scrollTop = 0;
  document.documentElement.scrollTop = 0;
}






</script>

	



</body>

</html>